name: reviewdog
on: [pull_request]
permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          fail_on_error: true
          token: ${{secrets.GITHUB_TOKEN}}